from enum import Enum


class Event(Enum):
    CONNECTION_OPENED = 'CONNECTION_OPENED'
    CONNECTION_CLOSED = 'CONNECTION_CLOSED'
    CONNECTION_FAILED = 'CONNECTION_FAILED'

    COMMAND_SENT = 'COMMAND_SENT'
    COMMAND_RESPONSE_RECEIVED = 'COMMAND_RESULT_RECEIVED'

    COMMAND_BUTTON_CLICKED = 'COMMAND_BUTTON_CLICKED'

    WARNING = 'WARNING'
